### ISSUE TITLE
[Ui] Criar o comando de publicação dos assets

### ISSUE THREAD

**Issue by irineujunior** [agenciafmd/admix-ui#2]
**Descrição**
Precisamos de um comando para publicar os assets do admix.
Vamos funcionar muito semelhante ao horizon e publicar os assets em /public/vendor/admix-ui/.

Ex.
`php artisan admix:ui-publish`

**Comment by milena-ramiro** [comment]
commit f056efa 
feat(UiPublishCommand): publica o tabler na public
